---
abstract: 'HTTP::Daemon over Unix sockets'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Daemon-UNIX
requires:
  HTTP::Daemon: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/HTTP-Daemon-UNIX/
  repository: http://github.com/sharyanto/perl-HTTP-Daemon-UNIX
version: 0.01
